1)import

The import attribute is used to import class,interface or all the members of a package.
It is similar to import keyword in java class or interface.  

Example of import attribute

1.<html>  
2.<body>  
3.  
4.<%@ page import="java.util.Date" %>  
5.Today is: <%= new Date() %>  
6.  
7.</body>  
8.</html> 

2)contentType

The contentType attribute defines the MIME(Multipurpose Internet Mail Extension) 
type of the HTTP response.The default value is "text/html;charset=ISO-8859-1". 

 Example of contentType attribute





1.<html>  
2.<body>  
3.  
4.<%@ page contentType=application/msword %>  
5.Today is: <%= new java.util.Date() %>  
6.  
7.</body>  
8.</html>  

 
3)extends

The extends attribute defines the parent class that will be inherited by the generated servlet.It is rarely used. 

 
4)info

This attribute simply sets the information of the JSP page which is retrieved later by using getServletInfo() method of Servlet interface. 

Example of info attribute





1.<html>  
2.<body>  
3.  
4.<%@ page info="composed by Sonoo Jaiswal" %>  
5.Today is: <%= new java.util.Date() %>  
6.  
7.</body>  
8.</html>  

The web container will create a method getServletInfo() in the resulting servlet.For example: 





1.public String getServletInfo() {  
2.  return "composed by Sonoo Jaiswal";   
3.}  

 
5)buffer

The buffer attribute sets the buffer size in kilobytes to handle output generated by the JSP page.The default size of the buffer is 8Kb.

Example of buffer attribute





1.<html>  
2.<body>  
3.  
4.<%@ page buffer="16kb" %>  
5.Today is: <%= new java.util.Date() %>  
6.  
7.</body>  
8.</html>  

 
6)language

The language attribute specifies the scripting language used in the JSP page. The default value is "java". 

 
7)isELIgnored

We can ignore the Expression Language (EL) in jsp by the isELIgnored attribute. By default its value is false i.e. Expression Language is enabled by default. We see Expression Language later. 





1.<%@ page isELIgnored="true" %>//Now EL will be ignored  

 
8)isThreadSafe

Servlet and JSP both are multithreaded.If you want to control this behaviour of JSP page, you can use isThreadSafe attribute of page directive.The value of isThreadSafe value is true.If you make it false, the web container will serialize the multiple requests, i.e. it will wait until the JSP finishes responding to a request before passing another request to it.If you make the value of isThreadSafe attribute like:  

<%@ page isThreadSafe="false" %>

The web container in such a case, will generate the servlet as:





1.public class SimplePage_jsp extends HttpJspBase   
2.  implements SingleThreadModel{  
3........  
4.}  

 
9)errorPage

The errorPage attribute is used to define the error page, if exception occurs in the current page, it will be redirected to the error page.

Example of errorPage attribute





1.//index.jsp  
2.<html>  
3.<body>  
4.  
5.<%@ page errorPage="myerrorpage.jsp" %>  
6.  
7. <%= 100/0 %>  
8.  
9.</body>  
10.</html>  

 
10)isErrorPage

The isErrorPage attribute is used to declare that the current page is the error page.

Note: The exception object can only be used in the error page.

Example of isErrorPage attribute





1.//myerrorpage.jsp  
2.<html>  
3.<body>  
4.  
5.<%@ page isErrorPage="true" %>  
6.  
7. Sorry an exception occured!<br/>  
8.The exception is: <%= exception %>  
9.  
10.</body>  
11.</html> 

