/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.22
 * Generated at: 2015-11-30 11:48:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Music_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Footer.html", Long.valueOf(1446390125744L));
    _jspx_dependants.put("/Header.html", Long.valueOf(1446527318354L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>MusicEra</title>\r\n");
      out.write("<link href=\"CSS/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"engine1/style.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"engine1/jquery.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link href=\"CSS/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("     <div id=\"menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"Music.jsp\">Home</a></li>\r\n");
      out.write("            <li><a href=\"AboutUs.jsp\">About Us</a></li>\r\n");
      out.write("            <li><a href=\"ContactUs.jsp\">Contact Us</a></li>\r\n");
      out.write("            <li><a href=\"Songs.jsp\">Songs</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("    <div id=\"main\" >\r\n");
      out.write("        <img src=\"Images/Me.png\" id=\"logo\">\r\n");
      out.write("        <h1 id=\"title\">Music Era</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <div id=\"music\">\r\n");
      out.write("\r\n");
      out.write("       <!-- Start WOWSlider.com BODY section -->\r\n");
      out.write("<div id=\"wowslider-container1\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"ws_images\">\r\n");
      out.write("<ul>\r\n");
      out.write("        <li><img src=\"data1/images/1398583043_shutterstock_54555799.jpg\" alt=\"The largest place to listen and download latest songs\" title=\"The largest place to listen and download latest songs\" id=\"wows1_0\"/></li>\r\n");
      out.write("        <li><a href=\"http://wowslider.com/vi\"><img src=\"data1/images/guitarinstrumentmusicalelectricstringsbrownblurwallpapersbytecom3840x2400.jpg\" alt=\"css slideshow\" title=\"Music Era : The Era Of Youth\" id=\"wows1_1\"/></a></li>\r\n");
      out.write("        <li><img src=\"data1/images/headphone.jpg\" alt=\"Are You Ready To Play With India's Best Music Store\" title=\"Are You Ready To Play With India's Best Music Store\" id=\"wows1_2\"/></li>\r\n");
      out.write("    </ul></div>\r\n");
      out.write("    <div class=\"ws_bullets\"><div>\r\n");
      out.write("        <a href=\"#\" title=\"The largest place to listen and download latest songs\"><span><img src=\"data1/tooltips/1398583043_shutterstock_54555799.jpg\" alt=\"The largest place to listen and download latest songs\"/>1</span></a>\r\n");
      out.write("        <a href=\"#\" title=\"Music Era : The Era Of Youth\"><span><img src=\"data1/tooltips/guitarinstrumentmusicalelectricstringsbrownblurwallpapersbytecom3840x2400.jpg\" alt=\"Music Era : The Era Of Youth\"/>2</span></a>\r\n");
      out.write("        <a href=\"#\" title=\"Are You Ready To Play With India's Best Music Store\"><span><img src=\"data1/tooltips/headphone.jpg\" alt=\"Are You Ready To Play With India's Best Music Store\"/>3</span></a>\r\n");
      out.write("    </div></div>    \r\n");
      out.write("    </div>\r\n");
      out.write("<div class=\"ws_shadow\"></div>\r\n");
      out.write(" \r\n");
      out.write("</div>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"engine1/wowslider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"engine1/script.js\"></script>\r\n");
      out.write("<!-- End WOWSlider.com BODY section -->\r\n");
      out.write("    \r\n");
      out.write("   ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link href=\"CSS/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("     <div id=\"footer\">\r\n");
      out.write("        <footer>\r\n");
      out.write("           <center> <p>Copyright &copy; <a href=\"#\">www.musicera.com</a> 2015 all right reserved</p></center>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
