/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.22
 * Generated at: 2015-10-29 17:08:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Career_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Footer.html", Long.valueOf(1446091400224L));
    _jspx_dependants.put("/Header.html", Long.valueOf(1446135086301L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Career</title>\r\n");
      out.write("<link href=\"CSS/header.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewreport\" content=\"width=device-width\">\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\">\r\n");
      out.write("function login(showhide){\r\n");
      out.write("if(showhide == \"show\"){\r\n");
      out.write("    document.getElementById('popDiv').style.display='block';\r\n");
      out.write("}else if(showhide == \"hide\"){\r\n");
      out.write("    document.getElementById('popDiv').style.display='none';\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("function register(showhide){\r\n");
      out.write("    if(showhide == \"show\"){\r\n");
      out.write("        document.getElementById('regDiv').style.display='block';\r\n");
      out.write("    }else if(showhide == \"hide\"){\r\n");
      out.write("        document.getElementById('regDiv').style.display='none';\r\n");
      out.write("    }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"CSS/header.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("    <div id=\"logo\">\r\n");
      out.write("        <img src=\"Images/unnamed.png\" style=\"width:210px; height:65px;\">\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#\">Home</a></li>\r\n");
      out.write("            <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("            <li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("            <li><a href=\"Career.jsp\">Career</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("     <div id=\"login\">\r\n");
      out.write("                <a href=\"javascript:login('show');\"  style=\"padding-right:20px;\">LOGIN</a>\r\n");
      out.write("                <a href=\"javascript:register('show');\" >SIGNUP</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"login\">\r\n");
      out.write("               <div id=\"popDiv\" class=\"ontop\"><a href=\"javascript:login('hide'); \" class=\"cancel\"  >&times;</a>\r\n");
      out.write("               <div id=\"popupbox\" ><div class=\"header\" > \r\n");
      out.write("            <form name=\"login\" action=\"authentication\" method=\"post\">\r\n");
      out.write("             <p>\r\n");
      out.write("            <input type=\"text\" name=\"userid\" id=\"userid\" class=\"textbox\" placeholder=\"name@example.com\">\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("    <p>\r\n");
      out.write("          <input type=\"password\" name=\"password\" id=\"password\" class=\"textbox\" placeholder=\"password\">\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("    <p class=\"login-submit\">\r\n");
      out.write("      <button type=\"submit\" id=\"button\">Login</button>    \r\n");
      out.write("     <a href=\"forgot.jsp\" style=\"padding-left: 35px; color: cyan;\">Forgot your password?</a></p>\r\n");
      out.write("</form>\r\n");
      out.write("<br />\r\n");
      out.write("        </div></div></div> \r\n");
      out.write("        <div id=\"regDiv\" class=\"back\"><div id=\"main\" class=\"register\">\r\n");
      out.write("        <a href=\"javascript:register('hide'); \" class=\"cancel\" >&times;</a>\r\n");
      out.write("        <center><div style=\"margin-top: 60px;\">\r\n");
      out.write("        <form action=\"register\" method=\"post\">\r\n");
      out.write("            <input type=\"text\" class=\"textbox\" name=\"email\" placeholder=\"email id\" /><br><br>\r\n");
      out.write("            <input type=\"text\"class=\"textbox\"name = \"user\"placeholder=\"user id\" maxlength=\"12\"><//><br><br>\r\n");
      out.write("            <input type=\"password\"class=\"textbox\"name = \"pass\"placeholder=\"password\"/><br><br>\r\n");
      out.write("            <input type=\"password\"class=\"textbox\"placeholder=\"confirm password\"/><br><br>\r\n");
      out.write("            <div style=\"width: 400px;\"><div style=\"float:left;width:200px;height:35px; border: solid 1px #666;border-top-left-radius: 5px;\r\n");
      out.write("    border-bottom-left-radius: 5px;box-shadow: 0px 0px 4px 0px #666;padding-top:10px;\">\r\n");
      out.write("            <input type=\"radio\" name=\"account\" value=\"Hire\">Hire</div>\r\n");
      out.write("            <div style=\"float:right;width:200px;height:35px;border: solid 1px #666;border-top-right-radius: 5px;\r\n");
      out.write("    border-bottom-right-radius: 5px; margin-top:-47px;box-shadow: 0px 0px 4px 0px #666;margin-right: -3px;padding-top:10px;\">\r\n");
      out.write("            <input type=\"radio\" name=\"account\" value=\"Work\">Work<br></div></div><br><br><br>\r\n");
      out.write("            <input type=\"submit\" value=\"Create Account\" id=\"button\"  name=\"reg\"/></form></div></center>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("          </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <div id=\"main2\">\r\n");
      out.write("        <center>\r\n");
      out.write("            <div id=\"data\">\r\n");
      out.write("            <form action=\"doctor\" method=\"post\">\r\n");
      out.write("            <center><h1>Information about Doctor</h1></center>\r\n");
      out.write("            <i><p style=\"color:red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.err}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p></i>\r\n");
      out.write("            <input type=\"text\" name=\"fname\" placeholder=\"First Name\" class=\"textbox\"/><br><br>\r\n");
      out.write("            <input type=\"text\" name=\"lname\"/ placeholder=\"Last Name\" class=\"textbox\"/><br><br>\r\n");
      out.write("            <img src=\"Images/find.png\" style=\"width: 24px; height: 24px;    margin-left: 9px; margin-top: 17px; position: absolute;\"/>\r\n");
      out.write("            <select name=\"doctors\" id=\"area2\">\r\n");
      out.write("             <option value=\"\">Specialitles</option>\r\n");
      out.write("               <option value=\"Dentist\">Dentist</option>\r\n");
      out.write("                <option value=\"Ophthalmologist\">Ophthalmologist</option>\r\n");
      out.write("                <option value=\"Dermatologist/Cos\">Dermatologist/Cos</option>\r\n");
      out.write("                <option value=\"Homeopath\">Homeopath</option>\r\n");
      out.write("                <option value=\"Ayurveda\">Ayurveda</option>\r\n");
      out.write("                <option value=\"Cardiologist\">Cardiologist</option>\r\n");
      out.write("                <option value=\"Gastroenterologist\">Gastroenterologist</option>\r\n");
      out.write("                <option value=\"Psychiatrist\">Psychiatrist</option>\r\n");
      out.write("                <option value=\"Ear-Nose-Throat (ENT)\">Ear-Nose-Throat (ENT)</option>\r\n");
      out.write("                <option value=\"Gynecologist/Obste\">Gynecologist/Obste</option>\r\n");
      out.write("                 <option value=\"Neurologist\">Neurologist</option>\r\n");
      out.write("                <option value=\"Urologist\">Urologist</option>\r\n");
      out.write("                \r\n");
      out.write("            </select><br>\r\n");
      out.write("            <img src=\"Images/location.png\" style=\"width: 30px; height: 30px;    margin-left: 7px; margin-top: 15px; position: absolute;\"/>\r\n");
      out.write("            <select name=\"location\" id=\"area2\">\r\n");
      out.write("                <option value=\"Delhi\">Delhi</option>\r\n");
      out.write("                <option value=\"Mumbai\">Mumbai</option>\r\n");
      out.write("                <option value=\"Bangalore\">Bangalore</option>\r\n");
      out.write("                <option value=\"Hyderabad\">Hyderabad</option>\r\n");
      out.write("                <option value=\"Kolkata\">Kolkata</option>\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <input type=\"submit\" value=\"Create Account\" id=\"button\"  name=\"reg\" style=\"float: left; margin-left: 143px; margin-top: 10px;\"/>\r\n");
      out.write("            </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </center>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link href=\"CSS/header.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("        <center>\r\n");
      out.write("            <div>\r\n");
      out.write("                <p>The Doctors copyright &copy; 2015 All right reserved<br>\r\n");
      out.write("                    <a href=\"#\">www.alldoctors.com</a>\r\n");
      out.write("                 </p>\r\n");
      out.write("          </center>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
