/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.22
 * Generated at: 2016-02-24 10:21:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class howwork_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/homeHeader.html", Long.valueOf(1442028192733L));
    _jspx_dependants.put("/pdetails.jsp", Long.valueOf(1440480071819L));
    _jspx_dependants.put("/footer.html", Long.valueOf(1440309035747L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>How it work</title>\r\n");
      out.write("<link href=\"CSS/header.css\" type=\"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div>\r\n");
      out.write("        ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewreport\" content=\"width=device-width\">\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\">\r\n");
      out.write("function login(showhide){\r\n");
      out.write("if(showhide == \"show\"){\r\n");
      out.write("    document.getElementById('popDiv').style.display='block';\r\n");
      out.write("}else if(showhide == \"hide\"){\r\n");
      out.write("    document.getElementById('popDiv').style.display='none';\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("function register(showhide){\r\n");
      out.write("    if(showhide == \"show\"){\r\n");
      out.write("        document.getElementById('regDiv').style.display='block';\r\n");
      out.write("    }else if(showhide == \"hide\"){\r\n");
      out.write("        document.getElementById('regDiv').style.display='none';\r\n");
      out.write("    }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"CSS/header.css\" type=\"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <div id=\"img\">\r\n");
      out.write("            <img src=\"images/coder.png\" style=\"width:100%; height:100%;\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("       <div id=\"menu\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"CoderHub.jsp\">Home</a></li>\r\n");
      out.write("                    <li><a href=\"work.jsp\">Work</a></li>\r\n");
      out.write("                    <li><a href=\"howwork.jsp\">How it work</a></li>\r\n");
      out.write("                    <li><a href=\"AboutUs.jsp\">About us</a></li>\r\n");
      out.write("                    <li><a href=\"ContacUs.jsp\">Contact us</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("         \r\n");
      out.write("          <div id=\"post\">\r\n");
      out.write("             <a href=\"postProjects.jsp\" >Post a project</a>\r\n");
      out.write("          </div>\r\n");
      out.write("           <div id=\"login\">\r\n");
      out.write("                <a href=\"javascript:login('show');\"  style=\"padding-right:20px;\">LOGIN</a>\r\n");
      out.write("                <a href=\"javascript:register('show');\" >SIGNUP</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"login\">\r\n");
      out.write("               <div id=\"popDiv\" class=\"ontop\"><a href=\"javascript:login('hide'); \" class=\"cancel\"  >&times;</a>\r\n");
      out.write("               <div id=\"popupbox\" ><div class=\"header\" > \r\n");
      out.write("            <form name=\"login\" action=\"authentication\" method=\"post\">\r\n");
      out.write("             <p>\r\n");
      out.write("            <input type=\"text\" name=\"userid\" id=\"userid\" class=\"textbox\" placeholder=\"name@example.com\">\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("    <p>\r\n");
      out.write("          <input type=\"password\" name=\"password\" id=\"password\" class=\"textbox\" placeholder=\"password\">\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("    <p class=\"login-submit\">\r\n");
      out.write("      <button type=\"submit\" id=\"button\">Login</button>    \r\n");
      out.write("     <a href=\"forgot.jsp\" style=\"padding-left: 35px;\">Forgot your password?</a></p>\r\n");
      out.write("</form>\r\n");
      out.write("<br />\r\n");
      out.write("        </div></div></div> \r\n");
      out.write("        <div id=\"regDiv\" class=\"back\"><div id=\"main\" class=\"register\">\r\n");
      out.write("        <a href=\"javascript:register('hide'); \" class=\"cancel\" >&times;</a>\r\n");
      out.write("        <center><div style=\"margin-top: 60px;\">\r\n");
      out.write("        <form action=\"register\" method=\"post\">\r\n");
      out.write("            <input type=\"text\" class=\"textbox\" name=\"email\" placeholder=\"email id\" /><br><br>\r\n");
      out.write("            <input type=\"text\"class=\"textbox\"name = \"user\"placeholder=\"user id\" maxlength=\"12\"><//><br><br>\r\n");
      out.write("            <input type=\"password\"class=\"textbox\"name = \"pass\"placeholder=\"password\"/><br><br>\r\n");
      out.write("            <input type=\"password\"class=\"textbox\"placeholder=\"confirm password\"/><br><br>\r\n");
      out.write("            <div style=\"width: 400px;\"><div style=\"float:left;width:200px;height:35px; border: solid 1px #666;border-top-left-radius: 5px;\r\n");
      out.write("    border-bottom-left-radius: 5px;box-shadow: 0px 0px 4px 0px #666;padding-top:10px;\">\r\n");
      out.write("            <input type=\"radio\" name=\"account\" value=\"Hire\">Hire</div>\r\n");
      out.write("            <div style=\"float:right;width:200px;height:35px;border: solid 1px #666;border-top-right-radius: 5px;\r\n");
      out.write("    border-bottom-right-radius: 5px; margin-top:-47px;box-shadow: 0px 0px 4px 0px #666;margin-right: -3px;padding-top:10px;\">\r\n");
      out.write("            <input type=\"radio\" name=\"account\" value=\"Work\">Work<br></div></div><br><br><br>\r\n");
      out.write("            <input type=\"submit\" value=\"Create Account\" id=\"button\"  name=\"reg\"/></form></div></center>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("          </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"howworkdiv\">\r\n");
      out.write("    <form action=\"postProjects.jsp\" method=\"post\">\r\n");
      out.write("        <center><h1 style=\"color:white;\">Need work done?</h1></center>\r\n");
      out.write("        <p style=\"color:white; padding-top: 15px; font-size:18px;text-align:center;\">\r\n");
      out.write("                Find the right person for the job here on CoderHub.com! With millions of <br>talented experts from all around the world,\r\n");
      out.write("                 you can get help with your<br> business within minutes of posting your project!\r\n");
      out.write("            </p>\r\n");
      out.write("            <center><input type=\"submit\" value=\"Post a project\" id=\"button\"/></center>\r\n");
      out.write("         </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <section >\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <div >\r\n");
      out.write("                    <div >\r\n");
      out.write("                        <span ></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <span >\r\n");
      out.write("                        <h3 style=\"color:#222;\">What kind of work can I get done?</h3>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            How does \"anything you want\" sound? We have experts representing every technical,\r\n");
      out.write("                             professional and creative field, providing a full range of solutions\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>Small jobs, large jobs, anything in-between</li>\r\n");
      out.write("                            <li>Fixed price or hourly terms</li>\r\n");
      out.write("                            <li>Specify your skills, cost and schedule requirements</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            Just give us the details of your project and our freelancers will get it done faster, better,\r\n");
      out.write("                             and cheaper than you can imagine. Your jobs can be as big or small as you like, they can be fixed price or hourly,\r\n");
      out.write("                              and you can specify the schedule, cost range, and milestones.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <div style=\"    background-color: whitesmoke;\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <span>\r\n");
      out.write("                        <h3 style=\"color:#222;\">How?</h3>\r\n");
      out.write("                        <ol >\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <strong>1. Post your project</strong><br>\r\n");
      out.write("                                It's always free to post your project. Invite our coders to submit bids,\r\n");
      out.write("                                 or browse relevant coders and make an offer. You'll have replies to your job within minutes!\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <strong>2. Choose the perfect coder</strong>\r\n");
      out.write("                                <ul >\r\n");
      out.write("                                    <li>Browse coders profiles</li>\r\n");
      out.write("                                    <li>Chat in real-time</li>\r\n");
      out.write("                                    <li>Compare proposals and select the best one</li>\r\n");
      out.write("                                    <li>Award your project and your coder goes to work</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <strong>3. Pay when you are satisfied!</strong><br>\r\n");
      out.write("                                Pay safely using our Milestone Payment system - release payments according to a schedule of goals you set,\r\n");
      out.write("                                 or pay only on completion. You decide, you are in control.\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <div >\r\n");
      out.write("                    <figure >\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <span >\r\n");
      out.write("                        <h3 style=\"color:#222;\">Be in Control. Keep in Contact.</h3>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            Freelancers use our Desktop App to track progress, monitor hours, communicate and share, and much more.\r\n");
      out.write("                             Always know what's going on with your project, what is getting done and what still needs doing.\r\n");
      out.write("                         </p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            Use our mobile app for easy messaging on-the-go.\r\n");
      out.write("                             You can always stay in touch with your freelancer when you have questions,\r\n");
      out.write("                             updates or need to share.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            Control project completion and pay. Release payment only when benchmarks are achieved,\r\n");
      out.write("                             or the project is completed to your satisfaction.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <div style=\" background-color: whitesmoke;\">\r\n");
      out.write("                    <figure >\r\n");
      out.write("                        <span ></span>\r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <span >\r\n");
      out.write("                        <h3 style=\"color:#222;\">Safety</h3>\r\n");
      out.write("                        <p>Freelancer.com is a community that values your trust and safety as our number one priority:</p>\r\n");
      out.write("                        <ul >\r\n");
      out.write("                            <li>\r\n");
      out.write("                                State-of-the-art security for your funds,\r\n");
      out.write("                                 all transactions are secured with GeoTrust 128-bit SSL encryption.\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                Our Milestone Payment system ensures your payments are released only when you are satisfied.\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                Our representatives are available 24/7 to assist if you have any problems.\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </section>\r\n");
      out.write("     <div id=\"howworkdiv\">\r\n");
      out.write("     <form action=\"postProjects.jsp\" method=\"post\">\r\n");
      out.write("           <center> <h2 style=\"font-size: 28pt; color:white;\">So what are you waiting for?</h2>\r\n");
      out.write("            <p style=\"font-size: 17pt; color:white;\">Post a project today and get bids from talented freelancers</p>\r\n");
      out.write("            <input type=\"submit\" value=\"Post a project\" id=\"button\"/></center>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link href=\"CSS/header.css\" type=\"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("     </div>\r\n");
      out.write("        <div id=\"projects\">\r\n");
      out.write("        <hr>\r\n");
      out.write("        <h5 style=\"float:left; padding-left: 50px;\">Projects</h3>\r\n");
      out.write("        <h5 style=\"float:right; padding-right: 50px;\">Registered Users</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link href=\"CSS/header.css\" type=\"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("            <center>\r\n");
      out.write("            <div style=\"margin-top: 25px;\">Copyright © 2048 CoderHub Pvt. Ltd <a href=\"http://www.coderhub.com\">www.CoderHub.com</a></div>\r\n");
      out.write("            </center>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
